paths:
  data: 'D:/Workspace/Machine_Learning/mlmed2025/Practice_1/data'
  model: 'D:/Workspace/Machine_Learning/mlmed2025/Practice_1/model'
  figure: 'D:/Workspace/Machine_Learning/mlmed2025/Practice_1/report/figures'